services:
  nginx:
    build: ./docker/files/nginx
    container_name: common-nginx
    volumes:
      - ./app:/data/www:rw
      - ./docker/files/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/files/nginx/certs/:/etc/nginx/certs
      - ./docker/files/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
    build: ./docker/files/mysql
    container_name: common-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql:rw
      - ./docker/logs/mysql:/var/lib/mysql-logs:rw
      - ./docker/files/mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-your_mysql_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-develop}
      MYSQL_USER: ${MYSQL_USER:-develop}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-your_mysql_password}
    restart: always

  redis-db:
    build: ./docker/files/redis
    container_name: common-redis
    ports:
      - "6380:6379"
    volumes:
      - ./docker/data/redis:/data
    restart: always

  postgres-db:
    build: ./docker/files/postgres
    container_name: common-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data:rw
      - ./docker/logs/postgres:/var/log/postgresql:rw
      - ./docker/files/postgres/conf.d:/etc/postgresql/conf.d:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-develop}
      POSTGRES_USER: ${POSTGRES_USER:-develop}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_postgres_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    restart: always
